apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headscale-subnet-router
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  prune: true
  wait: true
  targetNamespace: headscale-subnet-router
  dependsOn:
    - name: rook-ceph-cluster
    - name: external-secrets-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/headscale-subnet-router/app
