web:
  port: 80

ui:
  title: home-ops status

endpoints:
  - name: kubernetes-api
    group: internal
    url: https://kubernetes.default.svc.cluster.local
    interval: 60s
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
      - "[STATUS] == 401"
      - "[STATUS] == 403"

  - name: google
    group: external
    url: icmp://8.8.8.8
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
