apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - envoy-gateway/ks.yaml
  - cloudflared/ks.yaml
  - headscale-subnet-router/ks.yaml
  - gateway-api-crds
