apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: networking
spec:
  interval: 1h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    semver: "1.8.x"
